window.addEventListener("DOMContentLoaded",()=>{const search=new URLSearchParams(window.location.search);window.debug=search.has("debug");window.develop=search.has("develop");window.domain=search.has("domain")?search.get("domain"):window.location.origin;window.lang=search.has("lang")?search.get("lang"):"en";window.landing=search.has("landing")?Number(search.get("landing")):0;window.ready=false;});window.addEventListener("contextmenu",(event)=>{if(!window.debug){event.preventDefault();}});function switch_lang(selected){for(const localized of document.getElementsByClassName("localized")){if(localized.lang===selected){localized.classList.remove("hidden");}else{localized.classList.add("hidden");}}
for(const lang of document.getElementsByClassName("lang")){if(lang.lang===selected){lang.classList.remove("disabled");lang.classList.add("enabled");}else{lang.classList.remove("enabled");lang.classList.add("disabled");}}
document.getElementById("html").lang=selected;window.lang=selected;}
function build_locals(locals){locals.forEach(local=>{const button=document.createElement("div");button.classList.add("button","lang","disabled");button.lang=local;button.innerHTML=local
button.addEventListener("click",()=>{switch_lang(local);});document.getElementById("locals").appendChild(button);});}
function clear_content(){const content=document.getElementById("content");content.innerHTML="";}
function build_tabs(){const container=document.getElementById("tabs");const tabs=[{"text":"home","callback":Home.build},{"text":"portfolio","callback":Portfolio.build},{"text":"cv","callback":Resume.build}];tabs.forEach(tab=>{const button=document.createElement("div");button.classList.add("button","tab");button.innerHTML=tab.text
button.addEventListener("click",()=>{for(const other of document.getElementsByClassName("tab")){other.classList.add("disabled");}
button.classList.remove("disabled");const content=document.getElementById("content");clear_content();tab.callback();});container.appendChild(button);});container.getElementsByClassName("tab")[window.landing].click();}
window.addEventListener("load",()=>{build_tabs();build_locals(["en","de"]);switch_lang(window.lang);window.ready=true;document.getElementById("body").classList.remove("hidden");});