class Resume{static#build(data){const content=document.getElementById("content");const table=document.createElement("table");data.forEach(category=>{if(category.title){const tr=document.createElement("tr");const th=document.createElement("td");th.colSpan=2;th.classList.add("category-title");Object.keys(category.title).forEach(local=>{const span=document.createElement("span");span.classList.add("localized");span.lang=local;const text=document.createTextNode(category.title[local]);span.appendChild(text);th.appendChild(span);});tr.appendChild(th);table.appendChild(tr);}
if(category.timeline){category.timeline.forEach(group=>{const tbody=document.createElement("tbody");group.forEach(item=>{const tr=document.createElement("tr");{const td=document.createElement("td");td.classList.add("nowrap","right");const text=document.createTextNode(item.time);td.appendChild(text);tr.appendChild(td);}
{const td=document.createElement("td");const container=document.createElement("div");container.classList.add("container");if(item.highlight){container.classList.add("framed");}
Object.keys(item.item).forEach(local=>{const span=document.createElement("span");span.classList.add("localized");span.lang=local;if(item.href!==null){span.appendChild(document.createTextNode(item.item[local]));span.classList.add("link");const a=document.createElement("a");a.href=item.href;a.target="_blank";a.appendChild(span);const icon=document.createElement("span");icon.classList.add("open","localized","nowrap");icon.lang=local;{const span=document.createElement("span");span.classList.add("localized");span.lang="en";span.appendChild(document.createTextNode("[open]"));icon.appendChild(span);}
{const span=document.createElement("span");span.classList.add("localized");span.lang="de";span.appendChild(document.createTextNode("[öffnen]"));icon.appendChild(span);}
a.appendChild(icon);container.appendChild(a);}else{const text=document.createTextNode(item.item[local]);span.appendChild(text);container.appendChild(span);}});td.appendChild(container);tr.appendChild(td);}
tbody.appendChild(tr);});table.appendChild(tbody);});}});content.appendChild(table);{const div=document.createElement("div");div.classList.add("top");{const span=document.createElement("span");span.classList.add("localized");span.lang="en";span.appendChild(document.createTextNode("[to top]"));div.appendChild(span);}
{const span=document.createElement("span");span.classList.add("localized");span.lang="de";span.appendChild(document.createTextNode("[nach oben]"));div.appendChild(span);}
div.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"});});content.appendChild(div);}}
static build(){fetch("json/resume.json").then(response=>response.json()).then(data=>{Resume.#build(data.content);}).then(()=>{switch_lang(window.lang);}).catch(console.error);}}