name: GitHub Pages

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ trigger-workflow ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: false
    strategy:
      matrix:
        ref: [ master ]
        include:
          - ref: master
            path: .
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
          ref: ${{ matrix.ref }}
          path: ${{ matrix.path }}
          submodules: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.ref }}
          retention-days: 1
          if-no-files-found: error
          overwrite: true
          path: |
            ${{ matrix.path }}/web/index.html
            ${{ matrix.path }}/web/robots.txt
            ${{ matrix.path }}/web/sitemap.xml
            ${{ matrix.path }}/web/css/
            ${{ matrix.path }}/web/js/
            ${{ matrix.path }}/web/json/
            ${{ matrix.path }}/web/files/
            ${{ matrix.path }}/web/images/
            ${{ matrix.path }}/web/fonts/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Master Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-master
          path: .

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 1
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
